
package cl.clarochile.pdt.sur.msmont.ws.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import cl.clarochile.pdt.sur.msmont.ws.impl.type.ObjectFactory;
import cl.clarochile.pdt.sur.msmont.ws.impl.type.ZesCabCon;
import cl.clarochile.pdt.sur.msmont.ws.impl.type.ZesCabRes;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebService(name = "ZWS_MS_MONT_SUR", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style")
@XmlSeeAlso({ ObjectFactory.class })
public interface ZWSMSMONTSUR {


    /**
     *
     * @param iCabCon
     * @param numeroserie
     * @param idordenlegado
     * @param rutcliente
     * @param idcentroaliado
     * @param pais
     * @param contratocliente
     * @param fechainstalacion
     * @param razonsocial
     * @param comuna
     * @param tipocliente
     * @param rutsociedad
     * @param region
     * @param sku
     * @param nodo
     * @return
     *     returns cl.clarochile.pdt.sur.msmont.ws.impl.type.ZesCabRes
     */
    @WebMethod(operationName = "ZwsMsMontSur")
    @WebResult(name = "ECabRes", targetNamespace = "")
    @RequestWrapper(localName = "ZwsMsMontSur", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style",
                    className = "cl.clarochile.pdt.sur.msmont.ws.impl.type.ZwsMsMontSur")
    @ResponseWrapper(localName = "ZwsMsMontSurResponse",
                     targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style",
                     className = "cl.clarochile.pdt.sur.msmont.ws.impl.type.ZwsMsMontSurResponse")
    public ZesCabRes zwsMsMontSur(@WebParam(name = "Comuna", targetNamespace = "") String comuna,
                                  @WebParam(name = "Contratocliente", targetNamespace = "") String contratocliente,
                                  @WebParam(name = "Fechainstalacion", targetNamespace = "") String fechainstalacion,
                                  @WebParam(name = "ICabCon", targetNamespace = "") ZesCabCon iCabCon,
                                  @WebParam(name = "Idcentroaliado", targetNamespace = "") String idcentroaliado,
                                  @WebParam(name = "Idordenlegado", targetNamespace = "") String idordenlegado,
                                  @WebParam(name = "Nodo", targetNamespace = "") String nodo,
                                  @WebParam(name = "Numeroserie", targetNamespace = "") String numeroserie,
                                  @WebParam(name = "Pais", targetNamespace = "") String pais,
                                  @WebParam(name = "Razonsocial", targetNamespace = "") String razonsocial,
                                  @WebParam(name = "Region", targetNamespace = "") String region,
                                  @WebParam(name = "Rutcliente", targetNamespace = "") String rutcliente,
                                  @WebParam(name = "Rutsociedad", targetNamespace = "") String rutsociedad,
                                  @WebParam(name = "Sku", targetNamespace = "") String sku,
                                  @WebParam(name = "Tipocliente", targetNamespace = "") String tipocliente);

}
